-   repo: git://github.com/AStrangerGravity/pre-commit-hooks
    sha: 588b9f4b732aeca595b1e7220e9bf1c46fa13b14
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 0ff8620e03bf7acfb4dfdc86de14baf032c604f5
    hooks:
    -   id: trailing-whitespace
        files: ''
        args:
        - --no-markdown-linebreak-ext
    -   id: check-json
    -   id: check-yaml
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: 4972270a188e28f100cd0db472e05f59d9621e54
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
